package jp.asojuku.testmanagement.bo;

import java.sql.SQLException;

import javax.naming.NamingException;

import jp.asojuku.testmanagement.entity.TestListEntity;
import jp.asojuku.testmanagement.exception.SystemErrorExcepton;
import jp.asojuku.testmanagement.model.Dbcontrol;

public class DeleteTestInfoBo {
	private static final String TEST_INFO_DELETE_SQL ="DELETE FROM test "+
			"WHERE "+ TestListEntity.TEST_ID + " = ?";
	public void testdeleteinfo(String testId) throws  SystemErrorExcepton, NamingException{
		Dbcontrol db = new Dbcontrol();
		try{
			db.connect();
			
		}catch(NamingException e){
			System.out.println(e.getMessage());
			
		} catch (SQLException e) {
			System.out.println(e.getMessage());
			// TODO 自動生成された catch ブロック
			e.printStackTrace();
		}
		
	}
}
