package jp.asojuku.testmanagement.model;

import java.sql.PreparedStatement;
import java.sql.SQLException;

import javax.naming.InitialContext;
import javax.naming.NamingException;
import javax.sql.DataSource;


public class Dbcontrol {
	/*データベースに接続するクラス
	 * コネクトするメソッド
	 *
	 */
	public void connect() throws Exception{


		PreparedStatement ps = null;
		RequestDispatcher rd = null;
        	InitialContext ctx;
			try {
				ctx = new InitialContext();

	        	DataSource ds =
	        		(DataSource)ctx.lookup("java:comp/env/jdbc/myds");

				// MySQLに接続
		        con = ds.getConnection();

			} catch (NamingException e) {
				System.out.println(e);
				
			} catch (SQLException e) {
				System.out.println(e);
				
			}


	}
    //データベースを閉じる
	public void close(){

		if( con != null ){
			try {
				con.close();
			} catch (SQLException e) {
				// TODO 自動生成された catch ブロック
				e.printStackTrace();
				System.out.println("cloze No can do.");

			}
		}
	}

}
